import Foundation

enum HolyAgentStateBridgeError: Error, Equatable, LocalizedError {
    case malformedHooksContainer
    case malformedHookGroups(String)
    case malformedHookHandlers(String)

    var errorDescription: String? {
        switch self {
        case .malformedHooksContainer:
            "The hooks configuration is not a JSON object"
        case let .malformedHookGroups(event):
            "The hook groups for \(event) are malformed"
        case let .malformedHookHandlers(event):
            "A hook group for \(event) has malformed handlers"
        }
    }
}

/// Pure generators for the harness side of Holy's agent-state protocol.
///
/// The merge functions do not write user files and never touch Codex's hook
/// trust records. A UI integration can preview and explicitly write the
/// returned configuration while letting Codex perform its normal trust flow.
enum HolyAgentStateBridge {
    /// Generation ownership is deliberately separate from the v1 wire
    /// protocol. Bumping it lets the installer replace an older Holy-owned
    /// helper/plugin without treating a modified current generation as ours.
    static let generationVersion = 3
    static let openCodePluginFileName = "holy-agent-state.ts"
    static let codexNotifyAdapterFileName = "holy-codex-turn-complete.py"
    static let helperOwnershipMarkerPrefix =
        "# Generated by Holy Ghostty. Owner: com.holyghostty.agent-state.v"
    static let openCodePluginOwnershipMarkerPrefix =
        "// Generated by Holy Ghostty. Owner: com.holyghostty.agent-state.v"
    static let codexNotifyAdapterOwnershipMarkerPrefix =
        "# Generated by Holy Ghostty. Owner: com.holyghostty.codex-notify.v"
    static let codexNotifyConfigurationMarkerPrefix =
        "# Generated by Holy Ghostty. Owner: com.holyghostty.codex-notify-config.v"
    static let openCodePluginOwnershipMarker =
        "\(openCodePluginOwnershipMarkerPrefix)\(generationVersion)"
    static let helperOwnershipMarker =
        "\(helperOwnershipMarkerPrefix)\(generationVersion)"
    static let codexNotifyAdapterOwnershipMarker =
        "\(codexNotifyAdapterOwnershipMarkerPrefix)\(generationVersion)"
    static let codexNotifyConfigurationMarker =
        "\(codexNotifyConfigurationMarkerPrefix)\(generationVersion)"
    private static let legacyHelperOwnershipMarker =
        "# Generated by Holy Ghostty. Publishes lifecycle metadata only; never reads hook stdin."

    /// Merge supported Claude lifecycle hooks while retaining every unrelated
    /// setting, group, and handler. Only commands invoking this exact helper
    /// path with Holy's controlled metadata shape are considered owned.
    static func mergingClaudeSettings(
        _ settings: [String: Any],
        helperURL: URL
    ) throws -> [String: Any] {
        try mergingHooks(
            into: settings,
            source: HolyAgentStateSource.claude,
            helperURL: helperURL,
            specifications: claudeHookSpecifications
        )
    }

    /// Merge the stable Codex hook events. This intentionally returns only a
    /// hooks.json value: it does not read or mutate config.toml hook trust.
    static func mergingCodexHooks(
        _ hooksJSON: [String: Any],
        helperURL: URL
    ) throws -> [String: Any] {
        try mergingHooks(
            into: hooksJSON,
            source: HolyAgentStateSource.codex,
            helperURL: helperURL,
            specifications: codexHookSpecifications
        )
    }

    /// Current-generation ownership requires exact equality. A strictly older
    /// Holy generation marker is accepted so upgrades and uninstalls remain
    /// possible; unmarked, current-but-modified, and future files fail closed.
    static func isOwnedOpenCodePlugin(
        _ contents: String,
        helperURL: URL
    ) -> Bool {
        if contents == openCodePlugin(helperURL: helperURL) {
            return true
        }
        return isPriorGenerationMarker(
            in: contents,
            lineIndex: 0,
            markerPrefix: openCodePluginOwnershipMarkerPrefix
        )
    }

    /// The helper follows the same ownership contract as the OpenCode plugin.
    /// The unversioned marker recognizes only the one pre-versioning Holy
    /// helper already emitted; it exists solely to make that build upgradeable.
    static func isOwnedHelperScript(_ contents: String) -> Bool {
        if contents == helperScript {
            return true
        }
        let lines = contents.split(separator: "\n", omittingEmptySubsequences: false)
        guard lines.count > 1, lines[0] == "#!/bin/sh" else { return false }
        if lines[1] == Substring(legacyHelperOwnershipMarker) {
            return true
        }
        return isPriorGenerationMarker(
            in: contents,
            lineIndex: 1,
            markerPrefix: helperOwnershipMarkerPrefix
        )
    }

    /// Codex's top-level `notify` callback is the committed-turn producer.
    /// The generated adapter parses the one documented JSON argument and
    /// forwards only type/thread/turn identifiers. Prompt and response fields
    /// are never passed to the shared helper, logged, or written to disk.
    static func codexNotifyAdapter(helperURL: URL) -> String {
        let helperLiteral = pythonStringLiteral(helperURL.path)
        return #"""
        #!/usr/bin/env python3
        \#(codexNotifyAdapterOwnershipMarker)
        # Consumes only Codex's structured completion identity; never forwards text.

        import json
        import subprocess
        import sys

        HELPER = \#(helperLiteral)
        ALLOWED = frozenset("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._:/-")

        def metadata(value, maximum):
            return (
                isinstance(value, str)
                and 0 < len(value.encode("utf-8")) <= maximum
                and all(character in ALLOWED for character in value)
            )

        if len(sys.argv) != 2:
            raise SystemExit(64)

        try:
            payload = json.loads(sys.argv[1])
        except Exception:
            raise SystemExit(64)

        if not isinstance(payload, dict) or payload.get("type") != "agent-turn-complete":
            # Future notification types are not completion evidence.
            raise SystemExit(0)

        # Codex's documented payload carries turn-id only; thread-id is
        # accepted as optional enrichment if a future Codex adds it.
        thread_id = payload.get("thread-id")
        turn_id = payload.get("turn-id")
        if not metadata(turn_id, 64):
            raise SystemExit(64)
        if thread_id is not None and not metadata(thread_id, 64):
            raise SystemExit(64)

        completion_id = turn_id if thread_id is None else thread_id + ":" + turn_id
        if len(completion_id.encode("utf-8")) > 128:
            raise SystemExit(64)

        try:
            result = subprocess.run(
                [HELPER, "codex", "finished", "turn-finished", completion_id],
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=5,
                check=False,
                close_fds=True,
            )
        except Exception:
            raise SystemExit(1)
        raise SystemExit(result.returncode)
        """# + "\n"
    }

    static func isOwnedCodexNotifyAdapter(
        _ contents: String,
        helperURL: URL
    ) -> Bool {
        contents == codexNotifyAdapter(helperURL: helperURL)
    }

    /// Arguments only: callers retain control of the exact tmux socket/server
    /// prefix and never interpolate a pane target into shell source. Adoption
    /// must run this after it has positively resolved the pane it owns.
    static func tmuxOwnershipStampArguments(forTarget target: String) -> [String]? {
        let targetBytes = Array(target.utf8)
        let isPaneID = (2 ... 128).contains(targetBytes.count)
            && targetBytes.first == 37
            && targetBytes.dropFirst().allSatisfy { (48 ... 57).contains($0) }
        guard isPaneID || isMetadataIdentifier(target, maximumLength: 128) else { return nil }
        // Pane IDs stamp the exact pane; session names must stamp SESSION
        // scope — `-pq` against a session name resolves to only the active
        // pane, so adopted agents in other panes would read no owner. The
        // helper reads via `#{@option}` format expansion, which inherits
        // pane→session, so session scope reaches every pane.
        return [
            "set-option",
            isPaneID ? "-pq" : "-q",
            "-t",
            target,
            HolyAgentStateTransport.tmuxOwnershipOption,
            HolyAgentStateTransport.tmuxOwnershipValue,
        ]
    }

    /// Canonical adapter payload for an on-host remote transaction. The
    /// receiver merges `desiredRoot` into user JSON locally, so existing
    /// settings never leave that host. Relative paths are protocol assertions,
    /// not destinations the receiver may substitute.
    static func remoteInstallationManifest(helperURL: URL) throws -> Data {
        let adapterURL = helperURL.deletingLastPathComponent()
            .appendingPathComponent(codexNotifyAdapterFileName)
        let claudeRoot = try mergingClaudeSettings([:], helperURL: helperURL)
        let codexRoot = try mergingCodexHooks([:], helperURL: helperURL)
        let manifest: [String: Any] = [
            "protocolVersion": 1,
            "generationVersion": generationVersion,
            "lifecycleValues": HolyAgentLifecycleState.allCases.map(\.rawValue),
            "helper": [
                "relativePath": ".local/share/holy-ghostty/agent-state-hook.sh",
                "mode": 0o700,
                "content": helperScript,
                "ownershipMarkerPrefix": helperOwnershipMarkerPrefix,
            ],
            "hookDocuments": [
                [
                    "id": "claude",
                    "source": HolyAgentStateSource.claude,
                    "relativePath": ".claude/settings.json",
                    "desiredRoot": claudeRoot,
                    "manualTrust": false,
                ],
                [
                    "id": "codex",
                    "source": HolyAgentStateSource.codex,
                    "relativePath": ".codex/hooks.json",
                    "desiredRoot": codexRoot,
                    "manualTrust": true,
                ],
            ],
            "guardedTextDocuments": [
                [
                    "id": "codex-notify-config",
                    "relativePath": ".codex/config.toml",
                    "guardedTopLevelKey": "notify",
                    "ownershipMarker": codexNotifyConfigurationMarker,
                    "desiredLine": codexNotifyConfigurationLine(adapterURL: adapterURL),
                ],
            ],
            "exactFiles": [
                [
                    "id": "opencode",
                    "relativePath": ".config/opencode/plugins/\(openCodePluginFileName)",
                    "mode": 0o600,
                    "content": openCodePlugin(helperURL: helperURL),
                    "ownershipMarkerPrefix": openCodePluginOwnershipMarkerPrefix,
                    "ownershipMarkerLine": 0,
                    "acceptPriorGeneration": true,
                ],
                [
                    "id": "codex-notify",
                    "relativePath": ".local/share/holy-ghostty/\(codexNotifyAdapterFileName)",
                    "mode": 0o700,
                    "content": codexNotifyAdapter(helperURL: helperURL),
                    "ownershipMarkerPrefix": codexNotifyAdapterOwnershipMarkerPrefix,
                    "ownershipMarkerLine": 1,
                    "acceptPriorGeneration": false,
                ],
            ],
        ]
        return try JSONSerialization.data(withJSONObject: manifest, options: [.sortedKeys])
    }

    /// OpenCode provides structured session events directly. The plugin first
    /// binds itself to the session that receives a human chat message, then
    /// ignores events for other sessions (including background agents) so a
    /// shared server cannot paint the wrong terminal pane.
    static func openCodePlugin(helperURL: URL) -> String {
        let helperLiteral = javascriptStringLiteral(helperURL.path)
        return #"""
        \#(openCodePluginOwnershipMarker)
        import type { Plugin } from "@opencode-ai/plugin"

        const helperPath = \#(helperLiteral)

        export const holyAgentStatePlugin: Plugin = async () => {
          let activeSessionID: string | undefined
          let lastLifecycle: string | undefined
          let pendingTerminalError = false

          async function publish(
            lifecycle: "working" | "needs-user" | "finished" | "failed" | "idle" | "ended",
            reason: string,
            sessionID: string,
          ) {
            if (!sessionID || sessionID !== activeSessionID) return
            if (lastLifecycle === lifecycle) return
            const child = Bun.spawn(
              [helperPath, "opencode", lifecycle, reason, sessionID],
              { stdin: "ignore", stdout: "ignore", stderr: "ignore" },
            )
            const exitCode = await child.exited
            if (exitCode === 0) lastLifecycle = lifecycle
          }

          return {
            "chat.message": async (input) => {
              activeSessionID = input.sessionID
              lastLifecycle = undefined
              pendingTerminalError = false
              await publish("working", "user-prompt", input.sessionID)
            },

            event: async ({ event }) => {
              const value = event as any
              const type = value?.type as string | undefined
              const properties = value?.properties ?? {}
              const sessionID =
                properties.sessionID ??
                properties.sessionId ??
                properties.info?.id
              if (!sessionID || sessionID !== activeSessionID) return

              switch (type) {
                case "session.status": {
                  const status = properties.status?.type
                  if (status === "busy" || status === "retry") {
                    pendingTerminalError = false
                    await publish("working", `session-${status}`, sessionID)
                  } else if (status === "idle") {
                    if (pendingTerminalError) {
                      await publish("failed", "session-error", sessionID)
                    } else {
                      await publish("finished", "session-idle", sessionID)
                    }
                    pendingTerminalError = false
                  }
                  break
                }
                case "session.idle":
                  if (pendingTerminalError) {
                    await publish("failed", "session-error", sessionID)
                  } else {
                    await publish("finished", "session-idle", sessionID)
                  }
                  pendingTerminalError = false
                  break
                case "permission.asked":
                case "permission.updated":
                  await publish("needs-user", "permission", sessionID)
                  break
                case "question.asked":
                  await publish("needs-user", "question", sessionID)
                  break
                case "permission.replied":
                case "question.replied":
                case "question.rejected":
                  await publish("working", "input-resolved", sessionID)
                  break
                case "session.error":
                  // OpenCode may retry after publishing this event. Wait for
                  // the committed idle transition; a retry/busy status clears
                  // the pending error instead of falsely asking for the user.
                  pendingTerminalError = true
                  break
                case "session.deleted":
                  await publish("ended", "session-ended", sessionID)
                  activeSessionID = undefined
                  lastLifecycle = undefined
                  pendingTerminalError = false
                  break
              }
            },
          }
        }
        """# + "\n"
    }

    /// A POSIX producer shared by Claude, Codex, OpenCode, and future harness
    /// adapters. It consumes only controlled command arguments; hook stdin is
    /// intentionally never read, which makes transcript leakage impossible.
    ///
    /// It publishes the latest envelope durably in a pane-scoped tmux option
    /// and immediately through Holy's reserved OSC 777 notification. Finished
    /// envelopes are also copied to an independent last-finished register.
    static let helperScript = #"""
    #!/bin/sh
    \#(helperOwnershipMarker)
    # Publishes lifecycle metadata only; never reads hook stdin.

    metadata_field_is_valid() {
      value=$1
      maximum=$2
      [ -n "$value" ] || return 1
      [ "${#value}" -le "$maximum" ] || return 1
      case "$value" in
        *[!ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._:/-]*) return 1 ;;
      esac
      return 0
    }

    [ "$#" -ge 2 ] && [ "$#" -le 4 ] || exit 64
    source=$1
    lifecycle=$2
    reason=${3:-}
    raw_session=${4:-}

    metadata_field_is_valid "$source" 48 || exit 64
    case "$lifecycle" in
      working|needs-user|finished|failed|idle|ended) ;;
      *) exit 64 ;;
    esac
    if [ -n "$reason" ]; then
      metadata_field_is_valid "$reason" 64 || exit 64
    fi

    # Session identifiers are optional adapter metadata. Strip anything that
    # is not in the wire alphabet rather than allowing it into the envelope.
    session=$(printf '%s' "$raw_session" | LC_ALL=C tr -cd 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._:/-' | cut -c1-128)

    # These hooks are user-global, but this transport belongs only to a Holy
    # managed tmux pane. In a normal terminal or headless harness run it is a
    # quiet no-op, and it must never emit Holy's reserved OSC into that tty.
    [ -n "${TMUX_PANE:-}" ] || exit 0
    command -v tmux >/dev/null 2>&1 || exit 0
    holy_owner=$(tmux display-message -p -t "$TMUX_PANE" '#{@holy_agent_state_owner_v1}' 2>/dev/null || true)
    holy_runtime=$(tmux display-message -p -t "$TMUX_PANE" '#{@holy_runtime}' 2>/dev/null || true)
    if [ "$holy_owner" != "holy" ] && [ -z "$holy_runtime" ]; then
      exit 0
    fi
    # OSC written directly by a pane is consumed by tmux. Enable the pane's
    # documented passthrough path before emitting the DCS-wrapped notification
    # below. `all` is required for agents in panes not currently visible; older
    # tmux builds that only understand on/off retain the visible-pane fallback.
    tmux set-option -pq -t "$TMUX_PANE" allow-passthrough all 2>/dev/null \
      || tmux set-option -pq -t "$TMUX_PANE" allow-passthrough on 2>/dev/null \
      || true

    if [ -x /usr/bin/python3 ]; then
      now_ms=$(/usr/bin/python3 -c 'import time; print(time.time_ns() // 1000000)' 2>/dev/null)
    else
      now_ms="$(date +%s)000"
    fi
    case "$now_ms" in
      ''|*[!0-9]*) exit 70 ;;
    esac

    previous=""
    reuse_previous=0
    if [ -n "${TMUX_PANE:-}" ] && command -v tmux >/dev/null 2>&1; then
      previous=$(tmux show-options -pqv -t "$TMUX_PANE" @holy_agent_state_v1 2>/dev/null || true)
      previous_source=$(printf '%s' "$previous" | cut -d '|' -f 2)
      previous_lifecycle=$(printf '%s' "$previous" | cut -d '|' -f 3)
      previous_session=$(printf '%s' "$previous" | cut -d '|' -f 6)
      previous_reason=$(printf '%s' "$previous" | cut -d '|' -f 7)
      if [ "$previous_source" = "$source" ] \
        && [ "$previous_lifecycle" = "$lifecycle" ] \
        && [ "$previous_session" = "$session" ] \
        && [ "$previous_reason" = "$reason" ]; then
        # Repeated delivery of the same still-current lifecycle fact is not a
        # new event. A real next turn first transitions through working, while
        # Codex also supplies a different turn identity in the session field.
        if [ "$lifecycle" != "finished" ]; then
          exit 0
        fi
        previous_finish=$(tmux show-options -pqv -t "$TMUX_PANE" @holy_agent_last_finished_v1 2>/dev/null || true)
        if [ "$previous_finish" = "$previous" ]; then
          exit 0
        fi
        # The latest register committed but the independent finish register did
        # not. Repair the same event identity instead of minting a second reply.
        reuse_previous=1
      fi
      previous_ms=$(printf '%s' "$previous" | cut -d '|' -f 4)
      case "$previous_ms" in
        ''|*[!0-9]*) ;;
        *)
          if [ "$now_ms" -le "$previous_ms" ]; then
            now_ms=$((previous_ms + 1))
          fi
          ;;
      esac
    fi

    if [ "$reuse_previous" -eq 1 ]; then
      wire=$previous
    else
      event_token="$now_ms-$$"
      wire="v1|$source|$lifecycle|$now_ms|$event_token|$session|$reason"
    fi

    latest_persisted=0
    finish_persisted=1
    if [ -n "${TMUX_PANE:-}" ] && command -v tmux >/dev/null 2>&1; then
      if tmux set-option -pq -t "$TMUX_PANE" @holy_agent_state_v1 "$wire" 2>/dev/null; then
        latest_persisted=1
      fi
      if [ "$lifecycle" = "finished" ]; then
        finish_persisted=0
        if tmux set-option -pq -t "$TMUX_PANE" @holy_agent_last_finished_v1 "$wire" 2>/dev/null; then
          finish_persisted=1
        fi
      fi
    fi

    # OSC is only an acceleration path for an event that is already durable.
    # Its failure cannot erase a committed event, and its success cannot make
    # an unpersisted event look committed.
    if [ "$latest_persisted" -eq 1 ] && [ "$finish_persisted" -eq 1 ]; then
      tty_path=${HOLY_AGENT_STATE_TTY:-/dev/tty}
      if [ -w "$tty_path" ]; then
        printf '\033Ptmux;\033\033]777;notify;com.holyghostty.agent-state.v1;%s\007\033\\' "$wire" > "$tty_path" 2>/dev/null || true
      fi
    fi

    [ "$latest_persisted" -eq 1 ] || exit 1
    [ "$finish_persisted" -eq 1 ] || exit 1
    exit 0
    """# + "\n"

    private struct HookSpecification {
        let event: String
        let matcher: String?
        let lifecycle: HolyAgentLifecycleState
        let reasonCode: String
        /// Overrides the helper-based command entirely. Used by the watcher
        /// producer, which lives inline in the hook command so no second
        /// installed artifact is needed.
        var command: String? = nil
    }

    /// Marker embedded in the inline watcher program; ownership detection
    /// keys on it so merges stay idempotent and uninstall strips the hook.
    static let watcherHookCommandMarker = "holy-watcher-v1"

    /// Inline producer for the `@holy_watcher_v1` pane register (mn-f4d77b).
    /// A committed ScheduleWakeup means this session will reawaken itself;
    /// the program reads ONLY delaySeconds and stop from the tool input on
    /// stdin — never the loop prompt — and either arms the register with the
    /// computed fire time or clears it on stop. It always exits 0 so a
    /// register failure can never block the tool.
    static var claudeWatcherHookCommand: String {
        let program = """
        "\(watcherHookCommandMarker)"
        import json,os,subprocess,sys,time
        try:
         payload=json.load(sys.stdin)
        except Exception:
         sys.exit(0)
        tool_input=payload.get("tool_input") or {}
        pane=os.environ.get("TMUX_PANE")
        if not pane:
         sys.exit(0)
        if tool_input.get("stop") is True:
         subprocess.run(["tmux","set-option","-pqu","-t",pane,"@holy_watcher_v1"],check=False)
         sys.exit(0)
        delay=tool_input.get("delaySeconds")
        if not isinstance(delay,(int,float)) or isinstance(delay,bool) or delay<=0 or delay>86400:
         sys.exit(0)
        fire_at_ms=int(time.time()*1000)+int(delay*1000)
        wire="v1|claude|watching|%d|loop-wakeup" % fire_at_ms
        subprocess.run(["tmux","set-option","-pq","-t",pane,"@holy_watcher_v1",wire],check=False)
        sys.exit(0)
        """
        return "/usr/bin/python3 -c \(shellQuote(program))"
    }

    static func isOwnedWatcherHookCommand(_ command: String) -> Bool {
        command.hasPrefix("/usr/bin/python3 -c ")
            && command.contains(watcherHookCommandMarker)
    }

    private static let claudeHookSpecifications: [HookSpecification] = [
        .init(event: "SessionStart", matcher: nil, lifecycle: .idle, reasonCode: "session-start"),
        .init(event: "UserPromptSubmit", matcher: nil, lifecycle: .working, reasonCode: "user-prompt"),
        .init(event: "Notification", matcher: "permission_prompt", lifecycle: .needsUser, reasonCode: "permission"),
        // Claude Stop is a stop attempt — a parallel sibling hook can force
        // continuation, making an immediate `finished` transiently false. That
        // error self-corrects in seconds: the next tool or prompt event
        // publishes a newer working envelope and newest-wins ordering repairs
        // the state. The inverse failure proved unbounded in the field
        // (2026-07-21): idle_prompt has no latency SLA and does not fire for
        // focused sessions, leaving every watched turn-end stuck on working.
        // So Stop publishes finished, and idle_prompt stays as confirmation.
        .init(event: "Stop", matcher: nil, lifecycle: .finished, reasonCode: "turn-finished"),
        .init(event: "Notification", matcher: "idle_prompt", lifecycle: .finished, reasonCode: "idle-finished"),
        .init(event: "PostToolUse", matcher: nil, lifecycle: .working, reasonCode: "tool-complete"),
        // Watcher eye (mn-f4d77b): a scheduled /loop wakeup arms the
        // @holy_watcher_v1 register with its fire time; stop clears it.
        .init(
            event: "PostToolUse",
            matcher: "ScheduleWakeup",
            lifecycle: .idle,
            reasonCode: "wakeup-scheduled",
            command: claudeWatcherHookCommand
        ),
        .init(event: "StopFailure", matcher: nil, lifecycle: .failed, reasonCode: "turn-failed"),
        .init(event: "SessionEnd", matcher: nil, lifecycle: .ended, reasonCode: "session-ended"),
    ]

    private static let codexHookSpecifications: [HookSpecification] = [
        .init(event: "SessionStart", matcher: nil, lifecycle: .idle, reasonCode: "session-start"),
        .init(event: "UserPromptSubmit", matcher: nil, lifecycle: .working, reasonCode: "user-prompt"),
        // PreToolUse and PermissionRequest run before Codex aggregates every
        // matching hook. A sibling hook may answer or allow the request, so
        // neither event is committed evidence that the user is needed.
        .init(event: "PostToolUse", matcher: nil, lifecycle: .working, reasonCode: "tool-complete"),
    ]

    private static func mergingHooks(
        into root: [String: Any],
        source: String,
        helperURL: URL,
        specifications: [HookSpecification]
    ) throws -> [String: Any] {
        var result = root
        var hooks: [String: Any]
        if let existing = result["hooks"] {
            guard let dictionary = existing as? [String: Any] else {
                throw HolyAgentStateBridgeError.malformedHooksContainer
            }
            hooks = dictionary
        } else {
            hooks = [:]
        }

        let desiredByEvent = Dictionary(grouping: specifications, by: \.event)
        let allEvents = Set(hooks.keys).union(desiredByEvent.keys)

        for event in allEvents {
            var retainedGroups: [[String: Any]] = []
            var firstOwnedInsertionIndex: Int?
            if let groupsValue = hooks[event] {
                guard let groups = groupsValue as? [[String: Any]] else {
                    throw HolyAgentStateBridgeError.malformedHookGroups(event)
                }
                for existingGroup in groups {
                    guard let handlers = existingGroup["hooks"] as? [[String: Any]] else {
                        throw HolyAgentStateBridgeError.malformedHookHandlers(event)
                    }
                    let retainedHandlers = handlers.filter { handler in
                        guard let command = handler["command"] as? String else { return true }
                        return !isOwnedHookCommand(
                            command,
                            helperURL: helperURL,
                            source: source
                        ) && !isOwnedWatcherHookCommand(command)
                    }
                    if retainedHandlers.count != handlers.count,
                       firstOwnedInsertionIndex == nil {
                        firstOwnedInsertionIndex = retainedGroups.count
                    }
                    guard !retainedHandlers.isEmpty else { continue }
                    var retainedGroup = existingGroup
                    retainedGroup["hooks"] = retainedHandlers
                    retainedGroups.append(retainedGroup)
                }
            }

            let desiredGroups = (desiredByEvent[event] ?? []).map { specification in
                hookGroup(
                    specification,
                    source: source,
                    helperURL: helperURL
                )
            }
            let insertionIndex = min(
                firstOwnedInsertionIndex ?? retainedGroups.endIndex,
                retainedGroups.endIndex
            )
            retainedGroups.insert(contentsOf: desiredGroups, at: insertionIndex)

            if retainedGroups.isEmpty {
                hooks.removeValue(forKey: event)
            } else {
                hooks[event] = retainedGroups
            }
        }

        if hooks.isEmpty {
            result.removeValue(forKey: "hooks")
        } else {
            result["hooks"] = hooks
        }
        return result
    }

    private static func hookGroup(
        _ specification: HookSpecification,
        source: String,
        helperURL: URL
    ) -> [String: Any] {
        var group: [String: Any] = [
            "hooks": [
                [
                    "type": "command",
                    "command": specification.command ?? hookCommand(
                        helperURL: helperURL,
                        source: source,
                        lifecycle: specification.lifecycle,
                        reasonCode: specification.reasonCode
                    ),
                    "timeout": 5,
                ],
            ],
        ]
        if let matcher = specification.matcher {
            group["matcher"] = matcher
        }
        return group
    }

    private static func hookCommand(
        helperURL: URL,
        source: String,
        lifecycle: HolyAgentLifecycleState,
        reasonCode: String
    ) -> String {
        [
            shellQuote(helperURL.path),
            source,
            lifecycle.rawValue,
            reasonCode,
        ].joined(separator: " ")
    }

    static func isOwnedHookCommand(
        _ command: String,
        helperURL: URL,
        source: String
    ) -> Bool {
        let prefix = "\(shellQuote(helperURL.path)) \(source) "
        guard command.hasPrefix(prefix) else { return false }
        // Keep empty fields so irregular internal whitespace reads as foreign,
        // matching the remote Python's `split(" ")` — Holy never generates
        // doubled spaces, and local/remote must agree on ownership.
        let fields = command.dropFirst(prefix.count).split(separator: " ", omittingEmptySubsequences: false)
        guard fields.count == 2,
              HolyAgentLifecycleState(rawValue: String(fields[0])) != nil else {
            return false
        }
        return isMetadataIdentifier(String(fields[1]), maximumLength: 64)
    }

    private static func isMetadataIdentifier(
        _ value: String,
        maximumLength: Int
    ) -> Bool {
        guard !value.isEmpty, value.utf8.count <= maximumLength else { return false }
        return value.utf8.allSatisfy { byte in
            switch byte {
            case 45, 46, 47, 48 ... 57, 58, 65 ... 90, 95, 97 ... 122:
                true
            default:
                false
            }
        }
    }

    private static func shellQuote(_ value: String) -> String {
        "'\(value.replacingOccurrences(of: "'", with: "'\"'\"'"))'"
    }

    private static func isPriorGenerationMarker(
        in contents: String,
        lineIndex: Int,
        markerPrefix: String
    ) -> Bool {
        let lines = contents.split(separator: "\n", omittingEmptySubsequences: false)
        guard lines.indices.contains(lineIndex) else { return false }
        let line = String(lines[lineIndex])
        guard line.hasPrefix(markerPrefix) else { return false }
        let versionField = line.dropFirst(markerPrefix.count)
        guard !versionField.isEmpty,
              versionField.utf8.allSatisfy({ (48 ... 57).contains($0) }),
              let version = Int(versionField),
              version > 0,
              version < generationVersion else {
            return false
        }
        return true
    }

    private static func javascriptStringLiteral(_ value: String) -> String {
        guard let data = try? JSONSerialization.data(
            withJSONObject: value,
            options: [.fragmentsAllowed, .withoutEscapingSlashes]
        ), let literal = String(data: data, encoding: .utf8) else {
            preconditionFailure("A filesystem path must be JSON encodable")
        }
        return literal
    }

    private static func pythonStringLiteral(_ value: String) -> String {
        javascriptStringLiteral(value)
    }
}
